[package]
name = "todo"
version = "0.2.1"
authors = ["Todd Hainsworth <hainsworth.todd@gmail.com>"]

[dependencies]
serde = "1.0"
serde_json = "1.0"
serde_derive = "1.0"
dirs = "1.0"
colored = "1.6"
touch = "0"
